# Generated by Django 5.2.15 on 2026-06-30 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_travelpackage'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelpackage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='packages/'),
        ),
        migrations.AddField(
            model_name='trekkinggear',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gears/'),
        ),
    ]
