# Generated by Django 5.2.15 on 2026-06-30 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_travelpackage_image_trekkinggear_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='trekkinggear',
            name='description',
            field=models.TextField(default='No description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trekkinggear',
            name='features',
            field=models.TextField(blank=True, help_text='एक-एक लाइनमा फिचर्स लेख्नुहोस्'),
        ),
        migrations.AddField(
            model_name='trekkinggear',
            name='specifications',
            field=models.TextField(blank=True),
        ),
    ]
